server:
  port: 8763
  servlet:
    context-path: /cloud

spring:
  application:
    name: client2
    
str:
  s1: 123456

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/





